### ISSUE TITLE
Travis CI and docker-compose issues

### ISSUE THREAD

**Issue by sbesson** [ome/omero-plugins#23]
The cron-based Travis builds started to fail lately - see https://travis-ci.org/ome/omero-plugins/builds/595701347.

The issue is similar to the one discussed in https://travis-ci.community/t/problematic-docker-compose-version-1-23-1/5362:
- all Travis CI deployments are getting migrated to `xenial` rather than `trusty` (https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment)
- the `xenial` environment ships docker-compose 1.23.1 (https://docs.travis-ci.com/user/reference/xenial/#docker)
- the 1.23.0 version contains a change which introduced random strings in the container names at creation time. This has been flagged as a serious breaking change by the community and reduced in scope in the  1.23.2 version of `docker-compose`  (https://github.com/docker/compose/blob/1.23.2/CHANGELOG.md)

sbesson@c874909562fdc698167d5fbf082657d94ac42b31 is a potential workaround for solving the issue using the pre-installation approach mentioned in https://docs.travis-ci.com/user/docker/#using-docker-compose to install `docker-compose 1.23.2` which does not break `omero-test-infra` assumptions. A downside of this approach is that it needs to be opened against every repository consuming `omero-test-infra`.
Another approach would be to update `omero-test-infra` to compute the container ID without relying on the naming convention e.g. https://github.com/docker/compose/issues/6316#issuecomment-442231149

**Comment by will-moore** [comment]
So this is why travis is failing on https://github.com/ome/openmicroscopy/pull/6108? 
Definitely a blocker for me, so 👍 for any fix that works, thanks.

**Comment by manics** [comment]
Does the suggested fix in the first post (add `container_name` in `docker-compose.yml`) work?

**Comment by will-moore** [comment]
@manics Sorry, I'm not sure which of the links above you mean by the "first post". 
What change do you need to make to which file?
https://github.com/ome/omero-test-infra/blob/master/docker-compose.yml ?

**Comment by manics** [comment]
Sorry, I meant this post https://github.com/docker/compose/issues/6316#issue-376881016

Add `containername: <xxx>` to all services in https://github.com/ome/omero-test-infra/blob/master/docker-compose.yml to match what the scripts expect

**Comment by will-moore** [comment]
I'm looking at a bunch of scripts in https://github.com/ome/omero-test-infra but I can't see any container names.

Is it something like:
```
    omero:
        container_name: omero-server
```

**Comment by joshmoore** [comment]
Proposal PR opened.

**Comment by joshmoore** [comment]
https://github.com/ome/omero-test-infra/pull/43 is now merged and, e.g., https://github.com/ome/omero-figure/pull/342 went green. Closing and looking for jobs that need re-running. (Help appreciated there.)
